import {
  ClientboundCustomPayload,
  ClientboundFinishConfiguration,
  ClientboundRegistryData,
  ClientboundSelectKnownPacks,
  ClientboundUpdateEnabledFeatures,
  ClientboundUpdateTags,
  ServerboundClientInformation,
  ServerboundFinishConfiguration,
  ServerboundSelectKnownPacks,
} from "./config";
import { ServerboundIntention } from "./handshake";
import {
  ClientboundLoginCompression,
  ClientboundLoginDisconnect,
  ClientboundLoginFinished,
  ServerboundHello,
  ServerboundLoginAcknowledged,
} from "./login";
import {
  ClientboundAddEntity,
  ClientboundBundleDelimiter,
  ClientboundChangeDifficulty,
  ClientboundEntityEvent,
  ClientboundEntityPositionSync,
  ClientboundGameEvent,
  ClientboundInitializeBorder,
  ClientboundKeepAlive,
  ClientboundLogin,
  ClientboundMoveEntityPos,
  ClientboundMoveEntityPosRot,
  ClientboundMoveEntityRot,
  ClientboundPlayerAbilities,
  ClientboundPlayerPosition,
  ClientboundRecipeBookSettings,
  ClientboundRotateHead,
  ClientboundServerData,
  ClientboundSetChunkCacheCenter,
  ClientboundSetChunkCacheRadius,
  ClientboundSetDefaultSpawnPosition,
  ClientboundSetEntityMotion,
  ClientboundSetExperience,
  ClientboundSetHeldItem,
  ClientboundSetSimulationDistance,
  ClientboundSetSpawn,
  ClientboundSetTime,
  ClientboundSound,
  ClientboundSystemChat,
  ClientboundTickingState,
  ClientboundTickingStep,
  ClientboundUpdateAttributes,
  ClientboundUpdateRecipes,
  ServerboundKeepAlive,
} from "./play";

export const serverboundPackets = [
  ServerboundIntention,
  ServerboundHello,
  ServerboundLoginAcknowledged,
  ServerboundClientInformation,
  ServerboundSelectKnownPacks,
  ServerboundFinishConfiguration,
  ServerboundKeepAlive,
];

export const clientboundPackets = [
  ClientboundLoginCompression,
  ClientboundLoginFinished,
  ClientboundLoginDisconnect,
  ClientboundUpdateEnabledFeatures,
  ClientboundSelectKnownPacks,
  ClientboundRegistryData,
  ClientboundFinishConfiguration,
  ClientboundCustomPayload,
  ClientboundUpdateTags,
  ClientboundLogin,
  ClientboundChangeDifficulty,
  ClientboundPlayerAbilities,
  ClientboundSetHeldItem,
  ClientboundUpdateRecipes,
  ClientboundEntityEvent,
  ClientboundRecipeBookSettings,
  ClientboundPlayerPosition,
  ClientboundServerData,
  ClientboundSetSpawn,
  ClientboundSetExperience,
  ClientboundKeepAlive,
  ClientboundSound,
  ClientboundSetChunkCacheRadius,
  ClientboundSetSimulationDistance,
  ClientboundMoveEntityPosRot,
  ClientboundRotateHead,
  ClientboundMoveEntityPos,
  ClientboundSetEntityMotion,
  ClientboundEntityPositionSync,
  ClientboundSystemChat,
  ClientboundInitializeBorder,
  ClientboundSetDefaultSpawnPosition,
  ClientboundGameEvent,
  ClientboundTickingState,
  ClientboundTickingStep,
  ClientboundMoveEntityRot,
  ClientboundAddEntity,
  ClientboundBundleDelimiter,
  ClientboundUpdateAttributes,
  ClientboundSetChunkCacheCenter,
  ClientboundSetTime
];

export const packets = [...serverboundPackets, ...clientboundPackets];

export * from "./handshake";
export * from "./login";
export * from "./config";
export * from "./play";
